DEVDOCS-2570: Updated variant references and endpoint links
bigcommerce/dev-docs pull request #1012
Opened 2021-03-10 20:25 UTC by ektravel

# [DEVDOCS-2570](https://jira.bigcommerce.com/browse/DEVDOCS-2570)

## What changed?
* Updated variant option references and endpoint links

2021-03-16 20:02 UTC, markcmurphy requested changes
I know it was preexisting, but I spotted `PUT` as a verb and suggested a fix. Otherwise, good to go 👍

2021-03-17 14:43 UTC, ektravel commented
@uwikaiddi This PR is ready for your review.

2021-03-17 14:54 UTC, uwikaiddi commented on docs/api-docs/catalog/products-overview.md
> +[Products](/api-reference/store-management/catalog/products/getproducts) are the primary catalog entity, and the primary function of the eCommerce platform is to sell products on the storefront and o
```suggestion
[Products](/api-reference/store-management/catalog/products/getproducts) are the primary catalog entity, and the primary function of the ecommerce platform is to sell products on the storefront and other channels.

```

2021-03-17 14:54 UTC, uwikaiddi approved these changes

2021-03-17 14:54 UTC, merged