Updated program information
bigcommerce/dev-docs pull request #1050
Opened 2021-04-06 22:15 UTC by ektravel

# [DEVDOCS-2682](https://jira.bigcommerce.com/browse/DEVDOCS-2682)

## What changed?
* Added types of programs
* Updated resources
* Added training and support information

2021-04-07 19:12 UTC, traci707 requested changes
Just found a few small things.
FYI.
I removed technology from the link.
- [Applying to the Partner Program](#applying-to-the-partner-program)

2021-04-07 19:12 UTC, traci707 commented on docs/api-docs/partner/becoming-a-partner.md
> +To access the training modules, log into the [Partner Portal](https://partners.bigcommerce.com/), hover over the **Training** tab (top navigation), and select **eLearning Modules**. This will take yo
To access the training modules, log into the [Partner Portal](https://partners.bigcommerce.com/), hover over the **Training** tab (top navigation), and select **eLearning Modules**. This path will take you to the [Training & Enablement](https://partners.bigcommerce.com/English/Solutions/training/training_and_enablement.aspx) page.

2021-04-07 20:44 UTC, ektravel commented
@uwikaiddi This is PR is ready for review.

2021-04-13 17:22 UTC, uwikaiddi approved these changes

2021-04-13 17:22 UTC, merged