DEVDOCS-2541: Updated support resources
bigcommerce/dev-docs pull request #1051
Opened 2021-04-07 20:09 UTC by ektravel

# [DEVDOCS-2541](https://jira.bigcommerce.com/browse/DEVDOCS-2541)

## What changed?
* updated partner support resources

2021-04-09 13:53 UTC, traci707 commented on docs/api-docs/partner/support.md
> +You can access the Partner Support Team through the Partner Portal. Once you log into your Partner Portal account, hover over the **Support** tab located in the top right corner. Select **Contact Sup
You can access the Partner Support Team through the [Partner Portal](https://partners.bigcommerce.com/). Once you log into your Partner Portal account, hover over the **Support** tab located in the top right corner. Select **Contact Support** and you will be taken to a new page where you can **Create a Support Case** or use our **Live Chat** feature.

2021-04-09 14:34 UTC, traci707 commented on docs/api-docs/partner/dev-portal-overview.md
> +* [BigDesign Developer Playground](https://developer.bigcommerce.com/big-design/)
Remove * [BigDesign Developer Playground](https://developer.bigcommerce.com/big-design/) if listed under Tools.

2021-04-09 14:45 UTC, traci707 requested changes
Found a couple of small items. Good job Katya!

2021-04-09 14:45 UTC, traci707 commented on docs/api-docs/partner/support.md
> +BigCommerce has a dedicated Slack channel for Technology and Agency partners. It is a great place to connect, learn about new updates, and attend “Ask Me Anything” sessions with members of the BigCom
BigCommerce has a dedicated Slack channel for Technology and Agency partners. It is a great place to connect, learn about new updates, and attend “Ask Me Anything” sessions with the BigCommerce Product team members. To join the BigCommerce developer Slack community, fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSeQApTpd4T9lEX7hPgUjTyoq0vb8UbiCiWseuurJjdMHGBaGQ/viewform).

2021-04-09 15:05 UTC, ektravel commented
@uwikaiddi This PR is ready for your review.

2021-04-13 17:22 UTC, uwikaiddi approved these changes

2021-04-13 17:22 UTC, merged