DEVDOCS-2532
bigcommerce/dev-docs pull request #1106
Opened 2021-05-13 21:59 UTC by ektravel

# [DEVDOCS-2532](https://jira.bigcommerce.com/browse/DEVDOCS-2532)

## What changed?
* Added _Staying Current with Platform Updates_ article

2021-05-18 19:26 UTC, traci707 commented on docs/api-docs/partner/staying-current.md
> +As BigCommerce continues to deprecate V2 API endpoints and operations, consider migrating your store to the V3 API to take advantage of new features and improved performance. For more information on
As BigCommerce continues to deprecate V2 API endpoints and operations, consider migrating your store to the V3 API to take advantage of new features and improved performance. For more information on V3 improvements and learn about the differences between the V2 and V3 APIs, see [Difference between V2 and V3 Catalog REST APIs](https://developer.bigcommerce.com/api-docs/store-management/catalog/v2-vs-v3). To compare major V2 and V3 operations, see [V2 to V3 Catalog Operations Comparison](https://developer.bigcommerce.com/api-docs/store-management/catalog/v2-v3-examples). For planned deprecations and sunsets, refer to [Deprecations and Sunsets](https://developer.bigcommerce.com/api-docs/getting-started/deprecations-and-sunsets).

2021-05-18 19:26 UTC, traci707 commented on docs/api-docs/partner/staying-current.md
> +The Checkout JavaScript SDK and associated documentation is available from the [Checkout SDK repository](https://github.com/bigcommerce/checkout-sdk-js) in GitHub. Additionally, enterprise clients ca
The Checkout JavaScript SDK and associated documentation are available from the [Checkout SDK repository](https://github.com/bigcommerce/checkout-sdk-js) in GitHub. Additionally, enterprise clients can reach out to their account manager to review the services and resources available.

2021-05-18 21:22 UTC, ektravel commented on docs/api-docs/partner/staying-current.md
> +For recent updates to the Stencil's Cornerstone theme, we recommend setting up [a feed alert](https://developer.bigcommerce.com/changelog#feeds) for the [Developer Changelog](https://developer.bigcom
It takes a few seconds to load. https://developer.bigcommerce.com/changelog#feeds

2021-05-18 21:24 UTC, ektravel commented on docs/api-docs/partner/staying-current.md
> +For recent updates to the Stencil's Cornerstone theme, we recommend setting up [a feed alert](https://developer.bigcommerce.com/changelog#feeds) for the [Developer Changelog](https://developer.bigcom
The link works for me but it does take a few seconds to load.

2021-05-19 17:36 UTC, ektravel commented
@bookernath Can you please review this article for accuracy?

2021-05-28 14:48 UTC, ektravel commented
@uwikaiddi This PR is ready for final review.

2021-06-02 14:07 UTC, uwikaiddi requested changes

2021-06-02 14:07 UTC, uwikaiddi commented on docs/api-docs/partner/staying-current.md
> +The Checkout JavaScript SDK and associated documentation are available from the [Checkout SDK repository](https://github.com/bigcommerce/checkout-sdk-js). For information on [Optimized One-Page Check
@ektravel, a bit confusing having two links to click for information on Optimized One-Page Checkout. Best remove the link to support.

2021-06-02 14:07 UTC, uwikaiddi commented on docs/api-docs/partner/staying-current.md
> +For up-to-date information about the latest releases, new features, and bug fixes, we recommend setting up [a feed alert](https://developer.bigcommerce.com/changelog#feeds) for the [Developer Changel
```suggestion
For up-to-date information about the latest releases, new features, and bug fixes, we recommend setting up [a feed alert](https://developer.bigcommerce.com/changelog#feeds) for the [Developer Changelog](https://developer.bigcommerce.com/changelog). 

Additionally, you can gain more visibility into product updates by attending BigCommerce’s [Town Hall](https://support.bigcommerce.com/s/article/BigCommerce-Town-Halls) webinar programs and reading the [Product](https://support.bigcommerce.com/s/blog) and [Developer](https://medium.com/bigcommerce-developer-blog) blogs.
```

2021-06-02 14:07 UTC, uwikaiddi commented on docs/api-docs/partner/staying-current.md
> +
@ektravel, Since you mentioned setting up feeds in the General Updates section, there's no need to repeat the link in subsequent sections.

2021-06-02 21:21 UTC, uwikaiddi approved these changes

2021-06-02 21:21 UTC, merged