Update developers-headless-guide.md
bigcommerce/dev-docs pull request #1112
Opened 2021-05-19 14:45 UTC by traci707

# [DEVDOCS-2607](https://jira.bigcommerce.com/browse/DEVDOCS-2607)

## What changed?
Added a new sub-section called, "Managing access to your stencil site"

2021-05-19 15:57 UTC, RayeEThompson reviewed
Since we aren't going into the three ways, I think we can say something more like:
"The best way is to redirect..."

2021-05-21 17:19 UTC, markcmurphy requested changes

2021-05-21 19:07 UTC, markcmurphy approved these changes

2021-05-26 13:54 UTC, uwikaiddi approved these changes

2021-05-26 13:54 UTC, merged

2021-05-26 20:08 UTC, RayeEThompson reviewed
This looks great! Thank you, @traci707