Update live-previewing-a-theme.md
bigcommerce/dev-docs pull request #1118
Opened 2021-05-26 18:58 UTC by traci707

# [DEVDOCS-2813](https://jira.bigcommerce.com/browse/DEVDOCS-2813)

## What changed?
Updated Downloading a theme section

2021-05-26 19:59 UTC, junedkazi commented on docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md
> -* **Download your latest customizations** - download the theme's most recently saved version (appears only for themes customized for this store).
why are we removing this one ? Also I wonder if we even need this `Download Options` section for cli operations

2021-05-28 13:53 UTC, uwikaiddi requested changes

2021-05-28 13:53 UTC, uwikaiddi commented on docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md
> +Note: Downloading a theme does not include the current configuration of a theme. Run a [stencil pull](https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/stencil-cli-options-and-com
Please wrap this note in the appropriate <div> tags

2021-05-28 14:39 UTC, uwikaiddi approved these changes

2021-05-28 14:40 UTC, merged