DEVDOCS-2864: Document localizing widget template settings
bigcommerce/dev-docs pull request #1147
Opened 2021-06-29 15:48 UTC by ektravel

# [DEVDOCS-2864](https://jira.bigcommerce.com/browse/DEVDOCS-2864)

## What changed?
* added documentation on how to translate widget template settings using `schema_translations` property.

2021-06-29 18:12 UTC, markcmurphy commented on docs/api-docs/storefront/widgets/widgets-localizing-settings.md
> +4. Create a widget template by sending a `POST` request to the [Create a Widget Template](https://developer.bigcommerce.com/api-reference/store-management/widgets/widget-template/createwidgettemplate
```suggestion
4. Create a widget template by sending a `POST` request to the [Create a Widget Template](https://developer.bigcommerce.com/api-reference/store-management/widgets/widget-template/createwidgettemplate) endpoint. The following example creates a simple text widget:
```

2021-06-29 18:12 UTC, markcmurphy commented on docs/api-docs/storefront/widgets/widgets-localizing-settings.md
> +You can localize widget template settings to the provided language translations using the Internationalization (**i18n**) system.
```suggestion
You can localize widget template settings to the provided language translations using the internationalization (**i18n**) system.
```

2021-06-29 19:48 UTC, markcmurphy approved these changes

2021-06-29 20:43 UTC, kchu93 commented on docs/api-docs/storefront/widgets/widgets-localizing-settings.md
> +   "zh-CH": "线条颜色"
Hi Katya, would it be possible to change the chinese locale to `zh-CN`? Sorry for the miscommunication, but there was a very recent change to the way we are handling languageCodes and this should load the proper chinese setting.

2021-06-30 13:29 UTC, uwikaiddi commented on docs/api-docs/apps/guide/apps-12-requirements.md
> +- Make support resources available throughout the app, like during onboarding and on the app's dashboard within the BigCommerce iframe.
```suggestion
- Make support resources available throughout the app, like during onboarding and on the app's dashboard within the BigCommerce iFrame.

```

2021-07-01 00:48 UTC, kchu93 approved these changes
👍 LGTM

2021-07-07 14:33 UTC, uwikaiddi requested changes

2021-07-07 16:58 UTC, ektravel commented on docs/api-docs/storefront/widgets/widgets-localizing-settings.md
> +|Two-character language code|Multiple-character language code|
Reached out to Kevin Chu for more information.

2021-07-08 18:47 UTC, kchu93 commented on docs/api-docs/storefront/widgets/widgets-localizing-settings.md
> +|Two-character language code|Multiple-character language code|
👋 @uwikaiddi So this is a bit tricky and I have been trying to see if there is maybe a list of supported language Codes that BC could provide for developers, but as of right now, both 2 character languageCodes and multicharacter languageCodes are supported by themes + widgets. I know there is also some work being done by the translations team to convert 5 character codes into BC supported 2 character codes, but im not sure if that will be the standard moving forward or not. 

I can try to reach out to the translations team again to see if there is a set list of languageCodes we can provide our developers.

2021-07-08 19:20 UTC, ektravel commented on docs/api-docs/storefront/widgets/widgets-localizing-settings.md
> +|Two-character language code|Multiple-character language code|
@uwikaiddi For now, we are going to mention that widget templates support both [ISO 639‑1](https://en.wikipedia.org/wiki/ISO_639-1) and [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag) code schemes.

2021-07-08 19:21 UTC, ektravel commented
@uwikaiddi This PR is ready for review.

2021-07-13 13:18 UTC, uwikaiddi approved these changes

2021-07-13 13:18 UTC, merged