Devdocs-2961 update the documentation for transactional emails
bigcommerce/dev-docs pull request #1181
Opened 2021-07-28 18:43 UTC by markcmurphy

# [DEVDOCS-2910](https://jira.bigcommerce.com/browse/DEVDOCS-2910)

## What changed?
* add message regarding transactional email character limit

2021-07-28 19:22 UTC, traci707 reviewed
Do you think you can wrap this text in a note like the note at the bottom of the page?

Note
Omit ?channel_id to interact with global email templates.

2021-08-03 14:39 UTC, uwikaiddi approved these changes

2021-08-03 14:40 UTC, uwikaiddi requested changes

2021-08-03 14:40 UTC, uwikaiddi commented on docs/api-docs/management-apis/email-templates/overview.md
Agreed on @traci707 recommendation to wrap this in a note

2021-08-03 15:59 UTC, markcmurphy commented
> Do you think you can wrap this text in a note like the note at the bottom of the page?
> 
> Note
> Omit ?channel_id to interact with global email templates.

@traci707 @uwikaiddi Thanks, callout added

2021-08-04 10:22 UTC, uwikaiddi approved these changes

2021-08-04 10:22 UTC, merged