Update webhook-events.md
bigcommerce/dev-docs pull request #1378
Opened 2022-01-27 21:26 UTC by traci707

# [DEVDOCS-3412](https://jira.bigcommerce.com/browse/DEVDOCS-3412)

## What changed?
added text for the thumbnail field

2022-01-28 17:54 UTC, bc-andreadao requested changes

2022-01-28 17:54 UTC, bc-andreadao commented on docs/api-docs/getting-started/webhooks/webhook-events.md
> +- Thumbnail (new images only)
One important note/distinction that was mentioned in the ticket is that "The only thing that fires the updated event is when you go from having no thumbnail at all to a thumbnail," but uploading/updating a new image does not trigger an event. I think we may need to explicitly mention this.

2022-01-28 21:16 UTC, bc-andreadao commented on docs/api-docs/getting-started/webhooks/webhook-events.md
```suggestion

*Note that setting a thumbnail triggers an updated event only when that thumbnail is the first to be set. For example, setting an image as a thumbnail **after deleting all images** will trigger an updated event. However, changing the current thumbnail, uploading a new image and setting it as the thumbnail (while other thumbnails images exist), or even deleting all thumbnails does not generate an update event. 
```

2022-01-28 21:33 UTC, bc-andreadao approved these changes

2022-02-11 16:50 UTC, traci707 commented on docs/api-docs/getting-started/webhooks/webhook-events.md
> +\*Note that setting a thumbnail triggers an updated event only when that thumbnail is the first to be set. For example, setting an image as a thumbnail **after deleting all images** will trigger an u
@markcmurphy The `\` allows for the * to appear without changing the text to italics.

2022-02-17 17:37 UTC, merged