Update Channel-webhooks
bigcommerce/dev-docs pull request #1426
Opened 2022-03-09 21:48 UTC by traci707

# [DEVDOCS-3021](https://jira.bigcommerce.com/browse/DEVDOCS-3021)

## What changed?
* thing_that_changed

2022-03-14 09:50 UTC, kristinapototska requested changes

2022-03-14 09:50 UTC, kristinapototska commented on docs/api-docs/channels/channel-webhooks.md
> +| store/channel/{channel_id}/product/assigned            | New product assigned to channel (or new listing creating)      |
Product don't need to be new. Those webhooks would trigger when any product is assigned or unassigned to / from channel (via both catalog and listings API).

2022-04-01 07:08 UTC, slsriehl commented
@traci707 @markcmurphy I added more context for MSF and table columns with links to the endpoints that trigger these webhooks. Do we have a ticket to add these new MSF channel-specific webhooks to our list of schemas?

2022-04-01 07:11 UTC, slsriehl commented on docs/api-docs/channels/channel-webhooks.md
> +| store/channel/{channel_id}/settings/profile/updated    | Fires when the store profile settings that apply to the specified channel are updated | [Update store profile settings](/api-reference/store
@kristinapototska 
Does the `store/channel/{channel_id}/settings/profile/updated` webhook fire only when channel-specific overrides are updated, or also when global store settings are updated for which channel-specific overrides do not exist?

cc @traci707 @markcmurphy

2022-04-01 14:11 UTC, traci707 commented
@slsriehl Are you talking about [DEVDOCS-3021[(https://jira.bigcommerce.com/browse/DEVDOCS-3021)

2022-04-01 14:17 UTC, kristinapototska commented
@slsriehl given webhooks works as an overlay to fire every time store profile settings are updated in a way that affects channel you subscribed for. 
If you are subscribed to store profile changes per e.g. channel 5 and:
1. Given channel has store profile settings overridden – webhook would fire when given settings are updated on channel level.
2. Given channel is inheriting store profile settings from global level – webhook would fire when store profile settings are updated on global level which also has impact on given channel.


If there are 2 channels that are inheriting store profile settings from global level, when settings are changed on global level we would fire webhooks for each of those 2 channels.
This is going to work exactly the same for all the webhooks for settings where we have both global and channel level overrides.

2022-04-01 14:18 UTC, slsriehl commented
@traci707 I don't think so. What I mean to ask is whether the sidebar list of webhook subscription points on the `/api-reference` page is slated to be updated. If 3021 also includes those changes as part of the work, great. If not, we need to find/create a ticket for that.

2022-04-01 14:56 UTC, traci707 commented
@slsriehl I will create a separate ticket to update the side-bar links. I would like to get this PR merged.

2022-04-01 19:18 UTC, slsriehl approved these changes
@traci707 this is GTG from my POV. Please push back against my changes if you don't like them or they don't seem right.

2022-04-01 19:21 UTC, merged