DEVDOCS-3567 added category examples
bigcommerce/dev-docs pull request #1503
Opened 2022-05-17 21:31 UTC by bc-andreadao

# [DEVDOCS-3567](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3567)

Added example for category on stencil doc's graphql section

2022-05-17 21:33 UTC, bc-andreadao commented
Could use some help testing these. The graphQL code in the front matter block works on graphql playground when I tested it, but not sure about the handlebar example

2022-05-17 21:49 UTC, slsriehl commented on docs/stencil-docs/reference-docs/front-matter-reference.md
> +You can add [GraphQL Storefront API](/api-docs/storefront/graphql/graphql-storefront-api-overview) queries to your theme via the front matter block in a template file. For example, you can request a
```suggestion
You can add [GraphQL Storefront API](/api-docs/storefront/graphql/graphql-storefront-api-overview) queries to your theme using the front matter block in a template file. For example, you can request a product's variants by augmenting the existing [product.html template](https://github.com/bigcommerce/cornerstone/blob/master/templates/pages/product.html), or a category's products by augmenting the existing [category.html template](https://github.com/bigcommerce/cornerstone/blob/master/templates/pages/category.html): 

```

remove via, change `as well as` to `or` to further support the narrative that these are examples & there are a lot more possibilities.

2022-05-17 21:50 UTC, slsriehl commented on docs/stencil-docs/reference-docs/front-matter-reference.md
> +gql: "query categoryById ($categoryId: Int!){
yeah, testing is a good idea. are we sure that the `gql` attribute is all the way left?

2022-05-17 21:56 UTC, slsriehl commented on docs/stencil-docs/reference-docs/front-matter-reference.md
>  We suggest testing GraphQL queries using the [storefront API playground](https://developer.bigcommerce.com/graphql-playground) to refine them before adding them to your template. You can launch the p
```suggestion
We suggest testing and refining GraphQL queries before adding them to your template. You can use the [GraphQL Storefront API playground](https://developer.bigcommerce.com/graphql-playground). To launch the playground in the context of your store, navigate to the **Advanced Settings** menu in your store control panel and click the **Storefront API Playground** link.

```

@markcmurphy and I decided Friday that it's the GraphQL Storefront API, so made it say that. Also revised to leave more space for devs who have their own testing environments to drop out after we say "test it fam".

2022-05-17 22:15 UTC, slsriehl commented on docs/stencil-docs/reference-docs/front-matter-reference.md
> +Once you have added a query to your template's front matter block, execution happens automatically when the page loads. The data returned by the query will be returned in the page's context and made
we can do less in this paragraph.

Handlebars is the proper name of a library, so it should always be capitalized. `the handlebars` should be Handlebars; when `Handlebars` appears following a definite article, Handlebars is an adjective modifying `object`, `implementation`, `context`, or similar. https://handlebarsjs.com/

```suggestion
Templates with queries defined in their front matter automatically execute their queries on page load. You can access the returned data using the `gql` Handlebars object in the page's context. The following examples illustrate how to access `gql` object data using results from the previously-defined front matter queries:

```

2022-05-17 22:19 UTC, slsriehl commented on docs/stencil-docs/reference-docs/front-matter-reference.md
> +```handlebars title="Handlebar in product.html template" lineNumbers
```suggestion
```handlebars title="Example gql Handlebars object in product.html template" lineNumbers

```

2022-05-17 22:19 UTC, slsriehl commented on docs/stencil-docs/reference-docs/front-matter-reference.md
> +```handlebars title="Handlebar in category.html template" lineNumbers
```suggestion
```handlebars title="Example gql Handlebars object in category.html template" lineNumbers

```

2022-05-17 22:34 UTC, slsriehl requested changes
@bc-andreadao 

- I think @traci707 is the best person to help test the Stencil blocks. In addition to the actual objects, I am not sure the stuff inside your `{{# each}}` blocks is correctly scoped. Nested objects like this always need testing.
- Read through this article for other references to Handlebars and correct them per my comment. Alternatively, spin this bullet point off into another ticket.

2022-06-30 15:05 UTC, bc-andreadao commented
converted to draft, working on creating better examples

2022-08-06 09:12 UTC, slsriehl commented
Ticket paused.

2023-12-15 16:41 UTC, bc-andreadao commented
Closing, Stencil not prioritized for 2024 roadmap

2023-12-15 16:41 UTC, closed without merging