Devdocs 4484 update doc describing front matter
bigcommerce/dev-docs pull request #1652
Opened 2022-10-03 16:17 UTC by bc-traciporter

# [DEVDOCS-4484]

## What changed?
Added warning text in the Specifying custom front matter section.

## Anything else?

2022-10-04 06:06 UTC, bc-max requested changes

2022-10-04 06:06 UTC, bc-max commented on docs/stencil-docs/storefront-customization/custom-templates.md
> +The following example shows data you can inject into `templates/pages/brand.html` to access data in `templates/pages/custom/brand/custom-brand.html`. After [mapping](/stencil-docs/storefront-customiz
@bc-traciporter I believe we can remove lines 121 -123 above. Stencil-cli versions `5.2.1+` supports front matter on custom templates. So if a customer defines a custom template with a front matter in his local theme (in `config.stencil.json`), this front matter will be taken into account by stencil-cli. So you don't need to change default template/front matter as we use directly what we have in custom template.

2022-10-04 06:06 UTC, bc-max commented on docs/stencil-docs/storefront-customization/custom-templates.md
> +> When adding front matter directly to a custom template, Stencil CLI behaves as explained above. You must add front matter to the default template. However, when applying a theme to the storefront,
Stencil CLI starting from version `5.2.1` has the same behaviour as a regular mode (eg. live store) - both refular and CLI modes use front matter from custom template, not default one.

2022-10-05 06:49 UTC, bc-max requested changes

2022-10-05 06:49 UTC, bc-max commented on docs/stencil-docs/storefront-customization/custom-templates.md
> +When adding front matter directly to a custom template, you must add front matter to the default template when using Stencil CLI. However, when applying a theme to the storefront, it is possible to s
```suggestion
You can add front matter directly to a custom template. See [Using Front Matter](/stencil-docs/storefront-customization/using-front-matter) for more information on using front matter. 
```

2022-10-05 06:49 UTC, bc-max commented on docs/stencil-docs/storefront-customization/custom-templates.md
> +The following example shows data you can inject into `templates/pages/brand.html` to access data in `templates/pages/custom/brand/custom-brand.html`. After [mapping](/stencil-docs/storefront-customiz
It looks like you can completely delete line 123 as no injections to default template required.

2022-10-05 14:28 UTC, bc-max approved these changes

2022-10-27 00:53 UTC, stanzikratelbc submitted a review, later dismissed
LGTM. Ready to merge

2022-10-27 00:55 UTC, stanzikratelbc submitted a review, later dismissed
LGTM. Ready to merge and publish.

2022-10-28 19:49 UTC, stanzikratelbc approved these changes
LGTM. Ready to Merge

2022-10-31 14:04 UTC, merged