DEVDOCS-4819:[update] channels.mdx
bigcommerce/dev-docs pull request #1819
Opened 2023-03-13 17:50 UTC by bc-traciporter

# [DEVDOCS-4819]

## What changed?
Added limits to channels.mdx

## Anything else?
Related PRs, salient notes, etc

2023-03-15 11:03 UTC, kristinapototska requested changes

2023-03-15 11:03 UTC, kristinapototska commented on docs/api-docs/headless/channels.mdx
> +When the BigCommerce storefront status is `inactive` or `prelaunch`, one active headless storefront and a free store are allowed.
I think we would need to add more details here.
We need to mention that each store comes with 1 free active storefront. If merchants want this storefront to be headless – they need to set default BC storefront to `inactive` status and from there they can create `active` headless storefront within that 1 free storefront seat that comes with a store.

2023-03-15 11:03 UTC, kristinapototska commented on docs/api-docs/headless/channels.mdx
>  2. Pass that channel ID in a `POST` request to `/channels/{channel_id}/site` to create a site for the provided channel.
We also need to add additional steps here, that I've mentioned in the ticket.
Where developers need to:
1. Create site for headless channel which is going to be given channel primary domain.
2. Create checkout domain for given headless channel using https://developer.bigcommerce.com/docs/rest-management/channels/channel-site-checkout-url#upsert-a-site's-checkout-url
3. Add 3P SSL (optional) – https://developer.bigcommerce.com/docs/rest-management/sites/site-certificate#upsert-a-site%E2%80%99s-ssl/tls-certificate-information

2023-03-17 09:43 UTC, kristinapototska approved these changes

2023-03-20 16:41 UTC, bc-tgomez requested changes
The content changes look great! For the callout, we need to add a space before each sentence. [Nextra style guide for reference](https://mdx-components--bigcommerce-dev-center.netlify.app/components/callouts).

2023-03-20 16:41 UTC, bc-tgomez commented on docs/api-docs/headless/channels.mdx
> +Every store comes with a default limit of one active storefront that comes for free along with a store. The store can be used as a free sandbox while it is in inactive status. If you want also to mak
```suggestion
 Every store comes with a default limit of one active storefront that comes for free along with a store. The store can be used as a free sandbox while it is in inactive status. If you want also to make the store active, you need to purchase an additional storefront seat.
```

2023-03-22 16:48 UTC, merged