DEVDOCS-4828 remove all references to stoplight
bigcommerce/dev-docs pull request #1856
Opened 2023-03-29 15:46 UTC by stanzikratelbc

[DEVDOCS-4828]: removed references to Stoplight in multiple documents

2023-03-29 20:46 UTC, bc-tgomez submitted a review, later dismissed
Great edits! Some of the URLs are out of date and need replacing. **README.MD** has outdated URLs in Line 3. Also, I added a commit for minor linting issues.

2023-03-29 20:46 UTC, bc-tgomez commented on CONTRIBUTING.md
> +1. Navigate to the file in github ([making-requests.md](NEED NEW URL), for example)
Line 1 needs the new URL here.

2023-04-14 19:06 UTC, slsriehl commented on README.md
>  ├── pull_request_template_CODEOWNER.md # template for codeowner dev merges
```suggestion
```

2023-04-14 19:07 UTC, slsriehl commented on README.md
>  ├── pull_request_template_CODEOWNER.md # template for codeowner dev merges
codeowner template is elsewhere

2023-04-14 19:09 UTC, slsriehl commented on CONTRIBUTING.md
> +- [API Specification Style Guide](_project/_spec_style_guide.md)
(this comment is scope sprawl & should be used to make another ticket) --

I don't think we have this `_project` directory anymore, and the style guides almost certainly aren't current

2023-04-14 19:09 UTC, slsriehl commented on CONTRIBUTING.md
> +3. Make edits in your IDE of choice on a new branch
```suggestion
3. Make edits on a new branch in your IDE of choice.

```

2023-04-14 19:10 UTC, slsriehl commented on CONTRIBUTING.md
>  1. Fork `bigcommerce/dev-docs`
```suggestion
1. Fork `bigcommerce/dev-docs`.

```

2023-04-14 19:10 UTC, slsriehl commented on CONTRIBUTING.md
>  2. `git clone` the fork to your local machine
```suggestion
2. `git clone` the fork to your local machine.

```

2023-04-14 19:11 UTC, slsriehl commented on CONTRIBUTING.md
>  5. Create a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) against `bigcommerce/dev-docs/master`
```suggestion
5. Create a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) to `bigcommerce:dev-docs/main`.

```

2023-04-14 19:12 UTC, slsriehl commented on CONTRIBUTING.md
> +1. Navigate to the file in github ([making-requests.md](https://github.com/bigcommerce/dev-docs/blob/main/docs/api-docs/getting-started/making-requests.mdx), for example).
```suggestion
1. Navigate to the file in GitHub. For example, [making-requests.md](https://github.com/bigcommerce/dev-docs/blob/main/docs/api-docs/getting-started/making-requests.mdx).

```

2023-04-14 19:14 UTC, slsriehl commented on docs/api-docs/headless/customers.mdx
> -When querying the GraphQL Storefront API, customer-specific pricing will be reflected in query results if the customer is first logged in using the [customer login mutation](#) or a [customer imperso
why are we taking this first sentence out? it seems unrelated to the PR.

2023-04-14 19:15 UTC, slsriehl commented on docs/partner-apps/bundleb2b/b2b-edition.mdx
> -For the complete list of B3 API endpoints, see the [BundleB2B OpenAPI Documentation](https://bundleb2b.stoplight.io/).
this should stay. As of now, Bundle B2B still uses Stoplight.

2023-04-14 19:15 UTC, slsriehl commented on docs/partner-apps/bundleb2b/b2b-edition.mdx
```suggestion

For the complete list of B3 API endpoints, see the [BundleB2B OpenAPI Documentation](https://bundleb2b.stoplight.io/).
```

2023-04-14 19:15 UTC, slsriehl commented on docs/partner-apps/bundleb2b/b2b-edition.mdx
>  - [Quick Start](https://developer.bundleb2b.net/storefront/quick-start.html)
```suggestion
- [Quick Start](https://developer.bundleb2b.net/storefront/quick-start.html)
- [BundleB2B API Reference](https://bundleb2b.stoplight.io/)
```

2023-04-14 19:21 UTC, slsriehl requested changes
The main thing is that BundleB2B still uses Stoplight for their docs, so I made suggestions to leave theirs in.

I also made suggestions to add periods to a list of steps, like the other lists here.

Finally, the style guide recommends that we avoid parentheticals, so i've suggested that here.

2023-05-18 17:32 UTC, slsriehl commented on CONTRIBUTING.md
> +1. Navigate to the file in github ([making-requests.md](NEED NEW URL), for example)
added.

2023-05-18 17:32 UTC, slsriehl commented on docs/partner-apps/bundleb2b/b2b-edition.mdx
> -- [BundleB2B API Reference](https://bundleb2b.stoplight.io/)
overwritten by B2B article changes.

2023-05-18 17:56 UTC, slsriehl commented on README.md
> +This repository contains the markdown files and static assets powering [developer.bigcommerce.com](https://developer.bigcommerce.com/), which includes [API Docs](https://developer.bigcommerce.com/doc
```suggestion
This repository contains the markdown files and static assets powering [developer.bigcommerce.com](https://developer.bigcommerce.com/), which includes [API Docs](https://developer.bigcommerce.com/docs), [Theme Docs](https://developer.bigcommerce.com/stencil-docs), and [BigCommerce for WordPress](https://developer.bigcommerce.com/bigcommerce-for-wordpress/overview).

```

2023-05-18 18:04 UTC, slsriehl approved these changes

2023-05-18 18:59 UTC, merged