Update bundling and pushing.md
bigcommerce/dev-docs pull request #650
Opened 2020-09-04 19:56 UTC by traci707

# [DEVDOCS-2089](https://jira.bigcommerce.com/browse/DEVDOCS-2089)

## What changed?
Updated per refactor IA guidelines

2020-09-04 23:39 UTC, mikrdgz requested changes
This all looks good to me. The only change needed, I think, is adding a reminder somewhere that users should switch to OAuth if possible

[https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication#migrating-from-legacy-to-oauth](https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication#migrating-from-legacy-to-oauth)

2020-09-08 20:46 UTC, traci707 commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +Uploading your theme via the BigCommerce control panel's GUI is compatible with any store token (whether OAuth or Basic Auth), with any OAuth token scope, and with all versions of Stencil CLI. Howeve
```suggestion
Uploading your theme via the BigCommerce control panel's GUI is compatible with any store token (whether OAuth or Basic Auth) and with any OAuth token scope, and with all versions of Stencil CLI. We recommend for users to use OAuth if possible. However, this option requires that you first use a stencil bundle to package your theme into a .zip file. (Prepare your file according to Bundle only above.)

```

2020-09-09 11:52 UTC, uwikaiddi requested changes

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +If you have customized a theme initially downloaded from the BigCommerce Theme Marketplace: Before you package your theme, make sure your theme directory includes all the dependencies that BigCommerc
```suggestion
If you have customized a theme originally downloaded from the BigCommerce Theme Marketplace: Before you package your theme, make sure your theme directory includes all the dependencies that BigCommerce requires for submission.

```

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +Uploading your theme via the BigCommerce control panel's GUI is compatible with any store token (whether OAuth or Basic Auth), with any OAuth token scope, and with all versions of Stencil CLI. Howeve
```suggestion
Uploading your theme via the BigCommerce control panel's GUI is compatible with any store token (whether OAuth or Basic Auth), with any OAuth token scope, and with all versions of Stencil CLI. However, this option requires that you first use a stencil bundle to package your theme into a zip file. Prepare your file according to the instructions in the [Bundle only](#bundle-only) section.

```

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +* Do not open a bundled theme `.zip` file to add, delete, rename, or update files. Doing so will make your theme unusable in the production store.
```suggestion
* Do not open a bundled theme zip file to add, delete, rename, or update files. Doing so will make your theme unusable in the production store.

```

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +Check the resulting `.zip` file's size before you proceed. The zipped bundle should be only a few megabytes. BigCommerce imposes a hard limit of 50 MB, and any file size approaching that is problemat
```suggestion
Check the resulting zip file's size before you proceed. The zipped bundle should be only a few megabytes. BigCommerce imposes a hard limit of 50 MB, and any file size approaching that is problematic. If your zip file fits comfortably within the size limit above, jump directly to [Pushing Your Theme](https://developer.bigcommerce.com/stencil-docs/deploying-a-theme/bundling-and-pushing#pushing-your-theme). However, if your zip file approaches or exceeds 50 MB, you must first use one of these procedures to restructure your theme to a manageable size for upload to BigCommerce:

```
Style guide: [Referring to file types](https://intranet.bigcommerce.com/display/SST/Naming+Guidelines#NamingGuidelines-Referringtofiletypes)

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +Once you have verified the requirements above, you are ready to process and package your theme for upload to BigCommerce. Stencil CLI provides two options for creating a `.zip` file that contains all
```suggestion
Once you have verified the requirements above, you are ready to process and package your theme for upload to BigCommerce. Stencil CLI provides two options for creating a zip file that contains all of your theme's essentials while excluding redundant components. The options are either only bundling your theme, or bundling and pushing your theme. These options are available depending on how you've [authorized](https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/troubleshooting-your-setup#stencil-start-errors) your theme:

```

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +The stencil push command allows you to bundle your theme and upload it to the store, with a single terminal command. To run stencil push, you must first:
```suggestion
The `stencil push` command allows you to bundle your theme and upload it to the store, with a single terminal command. To run `stencil push`, you must first:

```

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +Successfully initialize your theme using an OAuth token that you created with the Themes: modify scope.
```suggestion
Successfully initialize your theme using an OAuth token that you created with the `Themes: modify scope`.

```

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +If you chose to apply the newly uploaded theme, you will receive the prompt: `Which variation would you like to apply? (Use arrow keys)`
```suggestion
If you chose to apply the newly uploaded theme, you will receive the prompt: "Which variation would you like to apply? (Use arrow keys)"

```

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +If you run `stencil push` when your store's `My Themes` section has reached its maximum of 20 themes, you will receive a prompt to select at least one existing theme for deletion.
```suggestion
If you run `stencil push` when your store's My Themes section has reached its maximum of 20 themes, you will receive a prompt to select at least one existing theme for deletion.

```

2020-09-09 11:52 UTC, uwikaiddi commented on docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
> +If you are certain of your selections, you can press `Enter` to delete the themes.
```suggestion
If you are certain of your selections, you can press **Enter** to delete the themes.

```

2020-09-09 14:16 UTC, uwikaiddi approved these changes

2020-09-09 14:16 UTC, merged