DEVDOCS-2175 WordPress Install Update
bigcommerce/dev-docs pull request #668
Opened 2020-09-10 17:35 UTC by ektravel

# [DEVDOCS-2175](https://jira.bigcommerce.com/browse/DEVDOCS-2175)

## What changed?
* updated system requirements
* updated formatting per style guide

2020-09-10 20:19 UTC, traci707 requested changes

2020-09-10 20:19 UTC, traci707 commented on docs/stencil-docs/developing-further/catalog-price-object.md
> +* **Default Price**
```suggestion
* **Default price**

```

2020-09-10 20:19 UTC, traci707 commented on docs/stencil-docs/developing-further/catalog-price-object.md
>  ### Related Articles
Related articles

2020-09-10 20:20 UTC, traci707 approved these changes

2020-09-10 20:22 UTC, traci707 reviewed
I think all the feedback has been given.

2020-09-10 20:25 UTC, traci707 reviewed
This page was already reviewed.

2020-09-10 20:25 UTC, traci707 commented on docs/stencil-docs/page-builder/configuration.md
> +### On This Page
```suggestion
### On this page
```

2020-09-10 20:26 UTC, traci707 approved these changes

2020-09-10 20:27 UTC, traci707 approved these changes

2020-09-10 20:28 UTC, traci707 approved these changes

2020-09-10 20:32 UTC, traci707 requested changes

2020-09-10 20:32 UTC, traci707 commented on docs/stencil-docs/page-builder/configuration.md
> +* For any theme setting, such as a Sass variable or a front-matter value, to be merchant-customizable, that setting and it's values must be present in `schema.json`. You have to manually provide thes
```suggestion
* For any theme setting, such as a Sass variable or a front-matter value, to be merchant-customizable, that setting and its values must be present in `schema.json`. You have to manually provide these declarations, according to the structure described here.
```

2020-09-10 20:32 UTC, traci707 commented on docs/stencil-docs/page-builder/configuration.md
> +* Each key that you create in `schema.json` must have a corresponding `config.json` key whose name matches its id value. This `config.json` key sets the default value even if that is an empty string.
```suggestion
* Each key that you create in `schema.json` must have a corresponding `config.json` key whose name matches its ID value. This `config.json` key sets the default value even if that is an empty string. A `schema.json` setting without an `id`-matched `config.json` key will not appear to users in the Page Builder UI.
```

2020-09-10 20:33 UTC, traci707 approved these changes

2020-09-10 20:38 UTC, traci707 requested changes

2020-09-10 20:38 UTC, traci707 commented on docs/stencil-docs/page-builder/configuration.md
> + Renaming a key | We do not recommend renaming keys. Instead, we recommend introducing a new key, while maintaining the old key until no one using an older version of your theme uses it.|
```suggestion
 Renaming a key | We do not recommend renaming keys. Instead, we recommend introducing a new key, while maintaining the old key until no one with an older version of your theme uses it.|
```

2020-09-10 20:39 UTC, traci707 reviewed
Either this definition or the new one is okay for Renaming a key

2020-09-10 20:40 UTC, traci707 approved these changes

2020-09-10 21:29 UTC, traci707 requested changes

2020-09-10 21:29 UTC, traci707 commented on docs/api-docs/storefront/graphql/graphql-api-examples.md
>  ### On this Page
On this page

2020-09-10 21:29 UTC, traci707 commented on docs/stencil-docs/developing-further/theme-updates-and-version-control.md
>  ### On This Page
On this page

2020-09-10 21:29 UTC, traci707 commented on docs/stencil-docs/localization/localizing-stores.md
>  ### Additional Resources
Additional resources

2020-09-15 18:51 UTC, uwikaiddi commented on docs/bigcommerce-for-wordpress/getting-started/install.md
> +## System requirements:
```suggestion
## System requirements

```

2020-09-15 18:51 UTC, uwikaiddi approved these changes

2020-09-15 18:51 UTC, merged