DEVDOCS-2178: Update Global Styles
bigcommerce/dev-docs pull request #681
Opened 2020-09-15 21:52 UTC by ektravel

# [DEVDOCS-2178](https://jira.bigcommerce.com/browse/DEVDOCS-2178)

## What changed?
* updated table of contents
* removed Store Design mention
* updated Models link
* minor formatting changes

2020-09-16 20:16 UTC, traci707 requested changes

2020-09-16 20:16 UTC, traci707 commented on docs/stencil-docs/configure-store-design-ui/defining-global-styles.md
> +The values that you define in the `config.json` file interact with local resources making it possible to customize your theme's appearance at a global level. Your `config.json` definitions set global
```suggestion
The values that you define in the `config.json` file interact with local resources making it possible to customize your theme's appearance globally. Your `config.json` definitions set global defaults for templates, front matter attributes, and Handlebars resources throughout your theme. You can also define custom variables in `config.json`, named according to your needs.

```

2020-09-16 21:50 UTC, ektravel commented on docs/stencil-docs/configure-store-design-ui/defining-global-styles.md
> +> Carefully check your theme against all the listed requirements – including the required keys within the `meta` object and `variations` array. While some requirements are not enforced in local devel
I think the meaning changes if we say "allowed" instead of "not enforced".

2020-09-17 13:24 UTC, uwikaiddi approved these changes

2020-09-17 13:24 UTC, merged