DEVDOCS-2215: Updated multisite section
bigcommerce/dev-docs pull request #686
Opened 2020-09-18 17:55 UTC by ektravel

# [DEVDOCS-2215](https://jira.bigcommerce.com/browse/DEVDOCS-2215)

## What changed?
* updated Multisite section
* removed Channel Name link (it just links installation )

2020-09-18 20:58 UTC, traci707 requested changes

2020-09-18 20:58 UTC, traci707 commented on docs/bigcommerce-for-wordpress/getting-started/install.md
> +Once connected, you will set up a new **Channel Name**. This name will be used to identify this specific WordPress instance in BigCommerce when checking orders or listing products.
```suggestion
Once connected, you will set up a new **Channel Name**. This name identifies this specific WordPress instance in BigCommerce when checking orders or listing products.

```

2020-09-24 12:08 UTC, uwikaiddi requested changes
@ektravel It looks like the same sections are repeated here. Can you confirm which version is correct and remove the other?

2020-09-24 14:55 UTC, ektravel commented
@uwikaiddi This PR contains changes made to **Multisite Instructions** which were not included on PR 673.

2020-09-25 12:14 UTC, uwikaiddi requested changes

2020-09-25 12:14 UTC, uwikaiddi commented on docs/bigcommerce-for-wordpress/getting-started/install.md
> +# Install
@ektravel, this section all the way down to Installation is a repeat.

2020-09-25 12:14 UTC, uwikaiddi commented on docs/bigcommerce-for-wordpress/getting-started/install.md
>  # Install
This section is repeated.

2020-09-25 16:17 UTC, closed without merging