Update checkout-sdk-example
bigcommerce/dev-docs pull request #692
Opened 2020-09-18 20:25 UTC by traci707

# [DEVDOCS-2203](https://jira.bigcommerce.com/browse/DEVDOCS-2203)

## What changed?
Removed all text that mentions editing the theme file
Added in steps for installing custom checkouts
Make a few editorial edits

2020-09-23 04:50 UTC, capsula4 commented on docs/stencil-docs/customizing-checkout/checkout-sdk-example.md
>  ### Congratulations!
this is no longer relevant, as `stencil start` is specific for theme integration..

2020-09-23 04:52 UTC, capsula4 commented
I'm tempted to remove this page altogeher, as the checkout-sdk-quickstart guide already explains how to use Open Source Checkout.

Back in the days, we have a Checkout SDK

2020-09-23 05:02 UTC, capsula4 commented on docs/stencil-docs/customizing-checkout/checkout-sdk-example.md
> +1. Navigate to the [Open source checkout](https://github.com/bigcommerce/checkout-js)repository.
I think we might want to keep the instructions of the checkout sdk example tied to the Checkout SDK Example repository. Will investigate what's required to do so.

2020-09-23 06:49 UTC, capsula4 commented
After taking a look, I think this page can be removed. Might be worth keeping the instructions inside the repo's README.

The only thing that should be required is to simply:
1. Build checkout file
2. Upload it to webdav
3. Paste webdav URL in CP Settings. 

These instructions are better suited to be kept in the github README. All dev docs pointing to this page should point instead directly to the GH repository: https://github.com/bigcommerce/checkout-sdk-js-example

2020-09-24 12:16 UTC, uwikaiddi requested changes

2020-09-24 12:16 UTC, uwikaiddi commented on docs/stencil-docs/customizing-checkout/checkout-sdk-example.md
> +### Creating a <span class ="fn">checkout-loader.js</span> file
```suggestion
### Creating a checkout-loader.js file

```

2020-09-24 23:43 UTC, capsula4 commented on docs/stencil-docs/customizing-checkout/checkout-sdk-example.md
> +### Creating a checkout-loader.js file
We have got this ticket https://jira.bigcommerce.com/browse/CHECKOUT-5191 to provide the checkout sdk with an checkout loader file. We shouldn't need to explain how to create the checkout loader file, it should come with the code, same way the open source checkout does it today.

Only instructions are:
1. Install dependencies (npm ci)
2. Build checkout (npm build)
3. Upload checkout-loader file
4. Enter checkout-loader URL in Control Panel

Sorry for the confusion, we have been discovering missing bits and pieces along the way, and the Checkout SDK Example is one of them.

2020-09-29 13:20 UTC, uwikaiddi commented
@traci707, does this still need to be merged, or was there a change to whether we were going through with this change?

2020-09-29 13:59 UTC, uwikaiddi approved these changes

2020-09-29 13:59 UTC, merged