DEVDOCS-2199: Add Filter Details
bigcommerce/dev-docs pull request #711
Opened 2020-09-28 21:58 UTC by ektravel

# [DEVDOCS-2199](https://jira.bigcommerce.com/browse/DEVDOCS-2199)

## What changed?
* added filer tables
* updated doc per style guide

2020-09-29 16:34 UTC, traci707 requested changes

2020-09-29 16:34 UTC, traci707 commented on docs/api-docs/getting-started/filtering.md
>  This will return page 2 of the results with 10 items per page.
```suggestion
`page=2&limit=10` will return page 2 of the results with 10 items per page.

```

2020-09-29 16:34 UTC, traci707 commented on docs/api-docs/getting-started/filtering.md
> +**Endpoints that support `include_fields` and `exclude_fields`.** (Last updated on 09/28/2020.)
```suggestion
**Endpoints that support `include_fields` and `exclude_fields` are listed below.** (Last updated on 09/28/2020.)

```

2020-09-29 16:34 UTC, traci707 commented on docs/api-docs/getting-started/filtering.md
> +|  | Get All Brands Metafields | `//catalog/brands/{brand_id}/metafields` |
```suggestion, should this be 
|  | Get All Brands Metafields | `/catalog/brands/{brand_id}/metafields` |

```

2020-09-29 16:34 UTC, traci707 commented on docs/api-docs/getting-started/filtering.md
> +**Endpoints that support `include`.** (Last updated on 09/28/2020.)
```suggestion
**Endpoints that support `include` are listed below.** (Last updated on 09/28/2020.)

```

2020-09-30 11:44 UTC, uwikaiddi approved these changes

2020-09-30 11:44 UTC, merged