Create a Sandbox Store.md
bigcommerce/dev-docs pull request #746
Opened 2020-10-08 16:03 UTC by traci707

# [DEVDOCS-2259](https://jira.bigcommerce.com/browse/DEVDOCS-2259)

## What changed?
Moved "Creating a Sandbox Store" from Becoming a partner.md to create this file.

2020-10-08 16:13 UTC, aglensmith requested changes

2020-10-08 16:13 UTC, aglensmith commented on docs/api-docs/partner/create-a-sandbox.md
> +
@traci707 Can you remove the extra lines between each step? They cause extra spacing when the doc is rendered.

2020-10-08 17:59 UTC, ektravel commented on docs/api-docs/partner/create-a-sandbox.md
> +
Can you please add an introductory sentence? Something like this:
```suggestion
In this article, we will walk you through the steps of creating a sandbox store. 
```

2020-10-08 17:59 UTC, ektravel reviewed
Finished my review.

2020-10-12 13:45 UTC, uwikaiddi approved these changes

2020-10-12 13:45 UTC, merged