Update apps-id.md
bigcommerce/dev-docs pull request #748
Opened 2020-10-08 20:47 UTC by traci707

# [DEVDOCS-2287](https://jira.bigcommerce.com/browse/DEVDOCS-2287)

## What changed?

- Changed devTools to Developer Portal
- Fixed the repeating sections

2020-10-09 22:51 UTC, ektravel commented on docs/api-docs/apps/tutorials/apps-id.md
> +- [Find in developer portal](#find-in-devtools)
```suggestion
- [Find in Developer Portal](#find-in-devtools)

```

2020-10-09 22:52 UTC, ektravel commented on docs/api-docs/apps/tutorials/apps-id.md
> +## Find in developer portal
```suggestion
## Find in Developer Portal

```

2020-10-09 22:52 UTC, ektravel reviewed
Finished my review.

2020-10-12 14:41 UTC, aglensmith requested changes
Remove empty line (line 8).

2020-10-12 14:41 UTC, aglensmith commented on docs/api-docs/apps/tutorials/apps-id.md
Remove empty line on line 8.

2020-10-12 14:53 UTC, aglensmith requested changes

2020-10-12 14:53 UTC, aglensmith commented on docs/api-docs/apps/tutorials/apps-id.md
> +
Remove this extra line.

2020-10-14 12:02 UTC, uwikaiddi approved these changes

2020-10-14 12:03 UTC, merged