DEVDOCS-2227: Section update
bigcommerce/dev-docs pull request #774
Opened 2020-10-15 17:40 UTC by ektravel

# [DEVDOCS-2227](https://jira.bigcommerce.com/browse/DEVDOCS-2227)

## What changed?
* added html & handlebars formatting
* added a link to cornerstone in guthub

2020-10-15 17:43 UTC, aglensmith requested changes

2020-10-15 17:43 UTC, aglensmith commented on docs/api-docs/storefront/widgets/widgets-overview.md
> +
```suggestion
```

2020-10-15 17:43 UTC, aglensmith commented on docs/api-docs/storefront/widgets/widgets-overview.md
> +
```suggestion
```

2020-10-15 17:43 UTC, aglensmith commented on docs/api-docs/storefront/widgets/widgets-overview.md
> +
```suggestion
```

2020-10-16 12:45 UTC, uwikaiddi commented
@ektravel, please resolve the merge conflicts for this first. I'' merge after.

2020-10-16 17:12 UTC, closed without merging