DEVDOCS-2339: Added Subscribers API definition
bigcommerce/dev-docs pull request #813
Opened 2020-10-23 17:55 UTC by ektravel

# [DEVDOCS-2339](https://jira.bigcommerce.com/browse/DEVDOCS-2339)

## What changed?
* added OAuth table
* updated OTP
* added Subscribers API definition

2020-10-23 18:02 UTC, aglensmith requested changes

2020-10-23 18:02 UTC, aglensmith commented on docs/api-docs/customers/customers-subscribers-overview.md
> +## Subscribers API
> The Subscribers API allows you to manage subscribers who have signed up for the store’s newsletter.

[the Storefront Email Subscriptions API](https://developer.bigcommerce.com/api-reference/storefront/storefront-subscriptions/subscription/postsubscriptions) is for creating or updating customer marketing email subscriptions. 

[Subscribers V3](https://developer.bigcommerce.com/api-reference/store-management/subscribers/subscribers/getsubscribers) is for managing subscriber customer accounts.

2020-10-26 17:19 UTC, aglensmith approved these changes

2020-10-27 13:35 UTC, uwikaiddi approved these changes

2020-10-27 13:36 UTC, uwikaiddi approved these changes

2020-10-27 13:36 UTC, merged