DEVDOCS-2354: Updated widgets tutorial
bigcommerce/dev-docs pull request #843
Opened 2020-11-05 19:14 UTC by ektravel

# [DEVDOCS-2354](https://jira.bigcommerce.com/browse/DEVDOCS-2354)

## What changed?
* updated code examples
* updated resources
* updated OTP

2020-11-05 19:30 UTC, traci707 requested changes

2020-11-05 19:30 UTC, traci707 commented on docs/api-docs/storefront/widgets/widgets-tutorial.md
> +`entity_id` depends on the type of page; for example, for product pages, it is the product ID, and for category pages, it is the category ID. To place your widget on a specific category page, you nee
`entity_id` depends on the type of page; for example, for product pages, it is the product ID, and for category pages, it is the category ID. To place your widget on a specific category page, you need to provide a category ID. To retrieve available category IDs, send a `GET` request to [`/v3/catalog/categories`](https://developer.bigcommerce.com/api-reference/store-management/catalog/category/getcategories). If you omit `entity_id`; the widget will appear on all of the category pages.

2020-11-05 19:48 UTC, traci707 approved these changes
LGTM

2020-11-06 16:06 UTC, uwikaiddi approved these changes

2020-11-06 16:06 UTC, merged