Update Current-Customer-API.md
bigcommerce/dev-docs pull request #844
Opened 2020-11-05 21:04 UTC by traci707

# [DEVDOCS-2098](https://jira.bigcommerce.com/browse/DEVDOCS-2098)

## What changed?
@aglensmith I tried to add more clarity to the [Current Customer API](https://developer.bigcommerce.com/api-docs/storefront/current-customer-api) article. I think the purpose of the API and how it is used have been addressed. 

As far as the examples, I think I need to keep the links but not sure what else is needed here. Nathan provided a code sample, https://github.com/bigcommerce/hello-world-app-ruby-sinatra#showing-the-recently-purchased-products-block-with-jwtbut, but not sure if it needs to be added. Can you provide more clarity?

2020-11-10 16:42 UTC, aglensmith submitted a review, later dismissed

2020-11-11 13:41 UTC, uwikaiddi requested changes

2020-11-11 13:41 UTC, uwikaiddi commented on docs/api-docs/customers/current-customer-api.md
> +To address this need, BigCommerce provides a Current Customer endpoint that your app can access via JavaScript on the storefront. This endpoint allows a remote application, such as a 3rd party subscr
```suggestion
To address this need, BigCommerce provides a Current Customer endpoint that your app can access via JavaScript on the storefront. This endpoint allows a remote application, such as a third-party subscription billing app, to return a JWT with identifying customer details. The information is signed with your [OAuth client secret](/api-docs/getting-started/basics/authentication#authentication_client-id-secret).

```
[Per style guide](https://intranet.bigcommerce.com/display/SST/Style+Guide+Word+List#StyleGuideWordList-T)

2020-11-11 13:41 UTC, uwikaiddi commented on docs/api-docs/customers/current-customer-api.md
> +Below is example JavaScript that will access this JWT. To test the JWT functionality, you can install this JavaScript on your sandbox BigCommerce store. You must include your application's client ID
```suggestion
Below is an example JavaScript code snippet that will access this JWT. To test the JWT functionality, you can install this JavaScript on your sandbox BigCommerce store. You must include your application's client ID in the request to identify the requesting application.

```

2020-11-12 02:36 UTC, uwikaiddi approved these changes

2020-11-12 02:36 UTC, uwikaiddi approved these changes

2020-11-12 02:36 UTC, merged

2020-11-13 04:15 UTC, bookernath commented
I'm late to the game, but just wanted to say this looks great 👍