DEVDOCS-2303: Created Widgets Versioning tutorial
bigcommerce/dev-docs pull request #848
Opened 2020-11-06 21:24 UTC by ektravel

# [DEVDOCS-2303](https://jira.bigcommerce.com/browse/DEVDOCS-2303)

## What changed?
* added a new tutorial
* added images

2020-11-09 21:16 UTC, traci707 approved these changes

2020-11-09 21:16 UTC, traci707 commented on docs/api-docs/storefront/widgets/widget-versioning-tutorial.md
> +You can view your widget template in the store's control panel using [Page Builder](https://support.bigcommerce.com/s/article/Page-Builder), BigCommerce's powerful theme customization tool. Your newl
You can view your widget template in the store's control panel using [Page Builder](https://support.bigcommerce.com/s/article/Page-Builder), BigCommerce's powerful theme customization tool. You can locate your newly created widget template in the left pane under **Custom**.

2020-11-09 21:16 UTC, traci707 commented on docs/api-docs/storefront/widgets/widget-versioning-tutorial.md
> +You will notice that `current_version_uuid` has changed and is now different from the widget's `version_uuid`. Although, we have updated the widget template, the widget created using that template di
You will notice that `current_version_uuid` has changed and is now different from the widget's `version_uuid`. Although we have updated the widget template, the widget created using that template did not change.

2020-11-09 21:16 UTC, traci707 commented on docs/api-docs/storefront/widgets/widget-versioning-tutorial.md
> +All widgets created after the update, will be based on the most current version. Let's create another widget to test this functionality.
All widgets created after the update will be based on the most current version. Let's create another widget to test this functionality.

2020-11-09 21:17 UTC, traci707 reviewed
LGTM

2020-11-11 13:45 UTC, uwikaiddi requested changes

2020-11-11 13:45 UTC, uwikaiddi commented on docs/api-docs/storefront/widgets/widget-versioning-tutorial.md
> +> * This tutorial uses [Cornerstone](https://github.com/bigcommerce/cornerstone) theme.
```suggestion
> This tutorial uses [Cornerstone](https://github.com/bigcommerce/cornerstone) theme.
```

2020-11-13 17:55 UTC, uwikaiddi approved these changes

2020-11-13 17:55 UTC, merged