DEVDOCS-2394: Updated Widgets API Overview
bigcommerce/dev-docs pull request #851
Opened 2020-11-11 20:59 UTC by ektravel

# [DEVDOCS-2394](https://jira.bigcommerce.com/browse/DEVDOCS-2394)

## What changed?
* updated OTP
* re-structured the order of Widgets Versioning 
* updated text

2020-11-12 17:02 UTC, traci707 reviewed
Comments added for Updated Widgets Overview.
I will review the Widgets Tutorial in a different PR.

2020-11-12 17:23 UTC, traci707 commented on docs/api-docs/storefront/widgets/widget-versioning-tutorial.md
> +### Create a new widget
Using widget versioning

2020-11-12 17:25 UTC, traci707 requested changes
I don't know if it makes sense or not but I wanted to change "Create a new widget". I don't think the subtitle is descriptive enough. My idea is to change it to "Using widget versioning" but let me know if you can think of something better.

2020-11-12 21:00 UTC, traci707 approved these changes

2020-11-13 18:12 UTC, uwikaiddi approved these changes

2020-11-13 18:12 UTC, merged