DEVDOCS-2389: Create a Global Regions Tutorial
bigcommerce/dev-docs pull request #853
Opened 2020-11-12 22:00 UTC by ektravel

# [DEVDOCS-](https://jira.bigcommerce.com/browse/DEVDOCS-)

## What changed?
* added the tutorial
* added a new image

2020-11-13 15:16 UTC, traci707 reviewed
Katya, the tutorial looks good. I just added the following suggestions to be more succinct and less wordy. However, it would be fine as it is.  You can decide which suggestions you want to incorporate.

2020-11-13 15:16 UTC, traci707 commented on docs/api-docs/storefront/widgets/global-regions-tutorial.md
> +To test the functionality of your global region, drag and drop one of the basic widgets from the left pane into the `below_content--global` region, then click **Preview**. You should see the widget y
To test your global region's functionality, drag and drop one of the basic widgets from the left pane into the `below_content--global` region, then click **Preview**. You should see the widget you just placed displayed on the home page and the category pages of your store.

2020-11-13 18:18 UTC, uwikaiddi requested changes

2020-11-13 18:18 UTC, uwikaiddi commented on docs/api-docs/storefront/widgets/global-regions-tutorial.md
> +- [Place a widget in the global region](#Place-a-widget-in-the-global-region)
```suggestion
- [Place a widget in the global region](#place-a-widget-in-the-global-region)
```

2020-11-13 18:21 UTC, uwikaiddi requested changes

2020-11-13 18:21 UTC, uwikaiddi commented on docs/api-docs/storefront/widgets/global-regions-tutorial.md
> +To test your global region's functionality, drag and drop one of the basic widgets from the left pane into the `below_content--global` region, then click **Preview**. You should see the widget you ju
Might be helpful to add an image of this step. Not sure if the image above does this since I can't view it yet.

2020-11-16 17:23 UTC, BC-EChristensen commented
this looks good to me!

2020-11-16 17:31 UTC, uwikaiddi approved these changes

2020-11-16 17:32 UTC, merged