Replace broken link with working link
bigcommerce/dev-docs pull request #896
Opened 2020-12-14 20:37 UTC by markcmurphy

# [DEVDOCS-2433](https://jira.bigcommerce.com/browse/DEVDOCS-2433)

## What changed?
Broken URLs were updated with working links to content

2020-12-14 21:29 UTC, traci707 requested changes
While in the file, I found a few instances of passive voice which I changed.  I also made an editorial change (vs.) and updated an endpoint name under related resources.

2020-12-14 21:29 UTC, traci707 commented on docs/api-docs/store-management/shipping/shipping-provider-api.md
>  - [Shipping](/api-docs/getting-started/webhooks/webhook-events#webhook-events_shipment)
- [Webhooks](/api-docs/getting-started/webhooks/webhook-events#webhook-events_shipment)

2020-12-14 21:29 UTC, traci707 commented on docs/api-docs/store-management/shipping/shipping-provider-api.md
>  - [Shipping Provider](/api-reference/store-management/shipping-provider-api)
- [Shipping Providers](/api-reference/store-management/shipping-provider-api)

2020-12-14 21:29 UTC, traci707 commented on docs/api-docs/store-management/shipping/shipping-provider-api.md
> +| Single Carrier vs Multi Carrier | A single carrier app will offer only one shipping provider. A multi carrier app will aggregate multiple shipping carriers in one app.
| Single Carrier vs. Multi Carrier | A single carrier app will offer only one shipping provider. A multi carrier app will aggregate multiple shipping carriers in one app.

2020-12-14 21:29 UTC, traci707 commented on docs/api-docs/store-management/shipping/shipping-provider-api.md
> +| Countries Available             | A list of countries where you can use the shipping carrier. The default behavior is that the carrier is available for every shipping origin. In most cases, this li
| Countries Available             | A list of countries where you can use the shipping carrier. The default behavior is that the carrier is available for every shipping origin. In most cases, this list should be as broad as possible. For example, if your carrier operates worldwide, make it available worldwide. You can limit the countries further than what the shipping carrier has provided. If the service is worldwide, then leave this field blank to specify that it is worldwide. Specifying the use of the shipping carrier is an optional step. |

2020-12-14 21:29 UTC, traci707 commented on docs/api-docs/store-management/shipping/shipping-provider-api.md
>  Shipping Provider endpoints can also be used by merchants to retrieve rates from custom shipping tables or an in-house shipping rate calculation service.
Merchants can also use shipping provider endpoints to retrieve rates from custom shipping tables or an in-house shipping rate calculation service.

2020-12-15 14:46 UTC, traci707 approved these changes

2020-12-15 14:52 UTC, uwikaiddi approved these changes

2020-12-15 14:52 UTC, merged