DEVDOCS-2445: Updated links, added reference to tutorials
bigcommerce/dev-docs pull request #905
Opened 2020-12-17 23:18 UTC by ektravel

# [DEVDOCS-2445](https://jira.bigcommerce.com/browse/DEVDOCS-2445)

## What changed?
* added reference to tutorials
* updated links

2020-12-18 15:07 UTC, traci707 requested changes

2020-12-18 15:07 UTC, traci707 commented on docs/stencil-docs/page-builder/page-builder-overview.md
> +For settings that can be passed as JSON objects into the `schema` property of the [Create a Widget Template](https://developer.bigcommerce.com/api-reference/store-management/widgets/widget-template/c
For settings that you can pass as JSON objects into the `schema` property of the [Create a Widget Template](https://developer.bigcommerce.com/api-reference/store-management/widgets/widget-template/createwidgettemplate) endpoint, see [Widgets UI Schema](https://developer.bigcommerce.com/stencil-docs/page-builder/widget-ui-schema).

2020-12-21 15:30 UTC, uwikaiddi commented on docs/stencil-docs/page-builder/page-builder-overview.md
> +As a theme developer, you can configure your theme's settings, determining how merchants can personalize your theme. For example, you can modify how merchants can customize colors, fonts, and the num
```suggestion
As a theme developer, you can configure your theme's settings to determine how merchants can personalize your theme. For example, you can modify how merchants can customize colors, fonts, and the number of products to display per feature. For information on how to configure your theme's files, see [Theme Styles Configuration](https://developer.bigcommerce.com/stencil-docs/page-builder/theme-styles-configuration). 
```

2020-12-21 15:30 UTC, uwikaiddi approved these changes

2020-12-21 15:31 UTC, merged