DEVDOCS-2471: updated placements list
bigcommerce/dev-docs pull request #918
Opened 2021-01-14 20:41 UTC by ektravel

# [DEVDOCS-2471](https://jira.bigcommerce.com/browse/DEVDOCS-2471)

## What changed?
* updated list of placements

2021-01-15 15:51 UTC, traci707 requested changes
I found a few small changes. I also updated the URL for the endpoints. It appears there are some redirects in place.

2021-01-15 15:51 UTC, traci707 commented on docs/api-docs/storefront/widgets/widgets-overview.md
>  | Widget templates | Widget templates are Handlebars-enabled HTML templates which define the widget’s structure on a page. These templates can include conditional logic as well as looping. *There is
| Widget templates | Widget templates are Handlebars-enabled HTML templates that define the widget's structure on a page. These templates can include conditional logic as well as looping. *There is a limit of `1,000` total custom widget templates per store. This limit does not include templates pre-provided by BigCommerce.* |

2021-01-15 15:51 UTC, traci707 commented on docs/api-docs/storefront/widgets/widgets-overview.md
>  | Widget configuration | This is a JSON payload that contains data used when rendering the widget. Each widget has a configuration, and there is a 64kb limit on the size of the JSON. The widget confi
Regions are specific spots in a Stencil template file where you can place widgets. Regions are defined at the theme file level using the following syntax: `{{{region name="..."}}}`. Many widgets can reside within a given region, and these widgets can have an assigned sort order. |
| Widget configuration | This is a JSON payload that contains data used when rendering the widget. Each widget has a configuration, and there is a 64kb limit on the JSON size. The widget configuration must be valid JSON, but we don’t enforce any additional configuration structure requirements. |

2021-01-15 15:51 UTC, traci707 commented on docs/api-docs/storefront/widgets/widgets-overview.md
>  * [Widgets API](/api-reference/storefront/widgets-api)
* [Widgets API](/api-reference/store-management/widgets)

2021-01-15 15:51 UTC, traci707 commented on docs/api-docs/storefront/widgets/widgets-overview.md
>  * [Widgets Tutorial](/api-docs/storefront/widgets/widgets-tutorial)
* [Widgets Tutorial](/api-docs/store-management/widgets/tutorials/tutorial)

2021-01-15 15:51 UTC, traci707 commented on docs/api-docs/storefront/widgets/widgets-overview.md
> +* [Widgets Code Samples](/api-docs/storefront/widgets/widgets-code-samples)
* [Widgets Code Samples](/api-docs/store-management/widgets/samples)

2021-01-19 20:39 UTC, uwikaiddi approved these changes

2021-01-19 20:40 UTC, merged