DEVDOCS-2487: Create Deprecations and Sunsets page
bigcommerce/dev-docs pull request #965
Opened 2021-02-09 22:54 UTC by ektravel

# [DEVDOCS-2487](https://jira.bigcommerce.com/browse/DEVDOCS-2487)

## What changed?
* added a stand alone Deprecations page

2021-02-10 14:44 UTC, traci707 requested changes

2021-02-10 14:44 UTC, traci707 commented on docs/api-docs/getting-started/deprecations-and-sunsets.md
> +The following endpoints are deprecated. We discourage using these endpoints as they are no longer supported by BigCommerce. Instead, consider using the provided V3 replacements.
The following endpoints are deprecated. We discourage using these endpoints as BigCommerce no longer supports them. Instead, consider using the provided V3 replacements.

2021-02-10 14:44 UTC, traci707 commented on docs/api-docs/getting-started/deprecations-and-sunsets.md
> +The following operations are scheduled to be removed.
BigCommerce has scheduled the removal of the following operations.

2021-02-10 14:44 UTC, traci707 commented on docs/api-docs/getting-started/deprecations-and-sunsets.md
> +The following properties are scheduled to be removed.
BigCommerce has scheduled the removal of the following properties.

2021-02-15 14:51 UTC, traci707 approved these changes
LGTM

2021-02-18 19:07 UTC, uwikaiddi commented on docs/api-docs/apps/guide/apps-05-oauth.md
> +> * As a best practice, your app should validate the list of scopes to ensure that it matches your app's needs and fail if it does not. At this time, the user can not pick and choose scopes. The dial
```suggestion
> * As a best practice, your app should validate the list of scopes to ensure that it matches your app's needs and fails if it does not. At this time, the user cannot pick and choose scopes. The dialog presented to the user requires the user to approve all scopes or none. For more information about available scopes, see [OAuth scopes](https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication#oauth-scopes).

```

2021-02-18 19:09 UTC, uwikaiddi approved these changes

2021-02-18 19:09 UTC, merged