Devdocs 2539 update next.js commerce content to mention store upgrades
bigcommerce/dev-docs pull request #968
Opened 2021-02-10 21:57 UTC by markcmurphy

# [DEVDOCS-2539](https://jira.bigcommerce.com/browse/DEVDOCS-2539)

## What changed?
* update next.js commerce content to mention store upgrades

2021-02-11 13:51 UTC, uwikaiddi requested changes

2021-02-11 13:51 UTC, uwikaiddi commented on docs/api-docs/building-storefronts/nextjs-commerce-guide.md
> +   2. If you are new to BigCommerce, select **Sign Up** to create a BigCommerce developer sandbox store and populate it with sample data. Vercel will connect Next.js Commerce to this sandbox store au
Find out who they should be contacting (phone, email, link to a form?) and link it here.

```suggestion
   2. If you are new to BigCommerce, select **Sign Up** to create a BigCommerce developer sandbox store and populate it with sample data. Vercel will connect Next.js Commerce to this sandbox store automatically. If you would later like to upgrade your sandbox store to a live store, [contact BigCommerce](#).
```

2021-02-26 13:38 UTC, uwikaiddi commented
@markcmurphy, still waiting on this update.

2021-03-01 18:51 UTC, markcmurphy commented
> @markcmurphy, still waiting on this update.

@uwikaiddi Ok, telephone number added

2021-03-05 13:22 UTC, uwikaiddi approved these changes

2021-03-05 13:23 UTC, merged