DEVDOCS-2528: Embedded Checkout Domain Setup
bigcommerce/dev-docs pull request #970
Opened 2021-02-11 17:01 UTC by aglensmith

# [DEVDOCS-](https://jira.bigcommerce.com/browse/DEVDOCS-2528)

## What changed?
* Added FAQ about domain setup requirement for safari compatibility.

2021-02-12 14:40 UTC, uwikaiddi commented
@aglensmith, request a peer review for this

2021-02-12 14:42 UTC, uwikaiddi requested changes
@aglensmith, request a peer review for this

2021-02-24 18:44 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +Embedded Checkout lets you place BigCommerce's checkout onto any website. Customers can check out on an external storefront while their order information syncs simultaneously to the BigCommerce Contr
```suggestion
Embedded Checkout lets you place BigCommerce's checkout onto any website. Customers can check out on an external storefront while their order information syncs simultaneously to the BigCommerce Control Panel. You can see this in action within the BigCommerce for WordPress plugin, which uses the same process described here as a checkout option for merchants. View more information about the plugin in the article [BigCommerce for WordPress](https://developer.bigcommerce.com/bigcommerce-for-wordpress/getting-started/introduction).
```

2021-02-24 18:55 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
>  You will need to use the [Channels, Sites, and Routes](https://developer.bigcommerce.com/api-reference/cart-checkout/channels-listings-api) APIs to embed checkout on an external site. The Channels AP
```suggestion
You will need to use the [Channels API](https://developer.bigcommerce.com/api-reference/store-management/channels) and the [Sites and Routes API](https://developer.bigcommerce.com/api-reference/store-management/sites) to embed checkout on an external site. The Channels API allows you to create and manage sales channel listings across a merchant's product catalog. A channel can be a marketplace, like Amazon, or an external storefront, like a WordPress site. The Sites and Routes API lets you set an external storefront domain and define the paths for important pages, like the home page, cart page, or checkout page. The Sites and Routes API allows you to link back to the proper URL from invoice emails and storefront links.
```

2021-02-24 18:57 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
>  Embedded Checkout requires the BigCommerce Checkout SDK to invoke a method to render the checkout in your site. Learn more about the [Checkout SDK](https://developer.bigcommerce.com/api-docs/cart-and
```suggestion
Embedded Checkout requires the BigCommerce [Checkout SDK](https://developer.bigcommerce.com/api-docs/cart-and-checkout/checkout-sdk) to invoke a method to render the checkout in your site.
```

2021-02-24 18:59 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
>  The [Customer Login API](https://developer.bigcommerce.com/api-docs/customers/customer-login-api) allows you to manage customers in two steps. First, you need to pass the `customer_id` when creating
```suggestion
The [Customer Login API](https://developer.bigcommerce.com/api-docs/customers/customer-login-api) allows you to manage customers in two steps. First, you need to pass the `customer_id` when creating the cart. Second, you need to log the customer in, so the session is active when the checkout loads.
```

2021-02-24 19:00 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Errors?**
```suggestion
### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Error?**
```

2021-02-24 19:03 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +In order for Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your Bi
```suggestion
For Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your BigCommerce storefront. For example, if your headless storefront is `www.mystore.com`, then your BigCommerce store's domain should be `checkout.mystore.com`. For more information on making Embedded Checkout on a headless WordPress storefront compatible with Safari, see [BigCommerce for WordPress](https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout#safari) in the Help Center. 

```

2021-02-24 19:25 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +To proceed to checkout, we'll need an active cart. To create one, send a `POST` request to the [Server-to-Server Cart API's](https://developer.bigcommerce.com/api-reference/cart-checkout/server-serve
```suggestion
To proceed to checkout, we'll need an active cart. To create one, send a `POST` request to the [Server-to-Server Cart API's](https://developer.bigcommerce.com/api-reference/store-management/carts)  `/cart` endpoint.
```

2021-02-24 19:26 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +Customers can log in using the [Customer Login API](https://developer.bigcommerce.com/api-docs/customers/customer-login-api#logging-in-a-customer).
```suggestion
Customers can log in using the [Customer Login API](https://developer.bigcommerce.com/api-docs/storefront/customer-login-api).
```

2021-02-24 19:28 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Errors?**
```suggestion
### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Error?**
```

2021-02-24 19:30 UTC, ektravel commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +In order for Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your Bi
```suggestion
For Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your BigCommerce storefront. For example, if your headless storefront is `www.mystore.com`, then your BigCommerce store's domain should be `checkout.mystore.com`. For more information on making Embedded Checkout on a headless WordPress storefront compatible with Safari, see [BigCommerce for WordPress](https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout#safari) in the Help Center. 
```

2021-02-24 19:31 UTC, ektravel reviewed
Added my comments.

2021-02-24 19:43 UTC, traci707 requested changes

2021-02-24 19:43 UTC, traci707 commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +Embedded Checkout lets you place BigCommerce's checkout onto any website. Customers can check out on an external storefront while their order information syncs simultaneously to the BigCommerce Contr
Embedded Checkout lets you place BigCommerce's checkout onto any website. Customers can check out on an external storefront while their order information syncs simultaneously to the BigCommerce control panel. You can see this in action within the BigCommerce for WordPress plugin, which uses the same process described here as a checkout option for merchants. View more information about the plugin in the article [BigCommerce for Wordpress](https://developer.bigcommerce.com/bigcommerce-for-wordpress/getting-started/introduction).

2021-02-24 19:43 UTC, traci707 commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
>  ## Logged-In customers
## Logged-in customers

2021-02-24 19:43 UTC, traci707 commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +In order for Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your Bi
For Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), you must serve your checkout page from the same domain as your BigCommerce storefront. For example, if your headless storefront is `www.mystore.com`, your BigCommerce store's domain should be `checkout.mystore.com`. See [BigCommerce for WordPress](https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout#safari) in the Help Center for more information on making Embedded Checkout on a headless WordPress storefront compatible with Safari.

2021-02-24 19:43 UTC, traci707 commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
>  > Channels created via API are visible in the BigCommerce store's Control Panel in **Products** > **Listed On**. The Orders section will now also include a filter for your channel.
> Channels created via API are visible in the BigCommerce store's control panel in **Products** > **Listed On**. The Orders section will now also include a filter for your channel.

2021-02-24 19:43 UTC, traci707 commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +To proceed to checkout, we'll need an active cart. To create one, send a `POST` request to the [Server-to-Server Cart API's](https://developer.bigcommerce.com/api-reference/cart-checkout/server-serve
To proceed to checkout, we'll need an active cart. To create one, send a `POST` request to the [Server-to-Server Cart API's](https://developer.bigcommerce.com/api-reference/cart-checkout/server-server-cart-api) `/cart` endpoint.

2021-02-24 19:43 UTC, traci707 commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +Customers can log in using the [Customer Login API](https://developer.bigcommerce.com/api-docs/customers/customer-login-api#logging-in-a-customer).
Customers can log in using the [Customer Login API](https://developer.bigcommerce.com/api-docs/storefront/customer-login-api).

2021-02-24 19:43 UTC, traci707 commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Errors?**
### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" errors?

2021-02-24 19:43 UTC, traci707 commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +In order for Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your Bi
For Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), you must serve your checkout page from the same domain as your BigCommerce storefront. For example, if your headless storefront is www.mystore.com, your BigCommerce store's domain should be checkout.mystore.com. See [BigCommerce for WordPress](https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout#safari) in the Help Center for more information on making Embedded Checkout on a headless WordPress storefront compatible with Safari.

2021-02-26 13:37 UTC, uwikaiddi requested changes

2021-02-26 13:37 UTC, uwikaiddi commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +Embedded Checkout lets you place BigCommerce's checkout onto any website. Customers can check out on an external storefront while their order information syncs simultaneously to the BigCommerce Contr
@aglensmith, the statements made here and the reference to BC4WP may no longer be true.
See https://bigcommerce.slack.com/archives/C57SQ401K/p1614112903001300.

2021-02-26 13:37 UTC, uwikaiddi commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +You will need to use the [Channels API](https://developer.bigcommerce.com/api-reference/store-management/channels) and the [Sites and Routes API](https://developer.bigcommerce.com/api-reference/store
```suggestion
You will need to use the [Channels API](https://developer.bigcommerce.com/api-reference/store-management/channels) and the [Sites and Routes API](https://developer.bigcommerce.com/api-reference/store-management/sites) to embed a checkout on an external site. The Channels API allows you to create and manage sales channel listings across a merchant's product catalog. A channel can be a marketplace, like Amazon, or an external storefront, like a WordPress site. The Sites and Routes API lets you set an external storefront domain and define the paths for important pages, like the home page, cart page, or checkout page. The Sites and Routes API allows you to link back to the proper URL from invoice emails and storefront links.
```

2021-03-03 14:17 UTC, uwikaiddi commented
@aglensmith, still waiting on these updates.

2021-03-10 17:20 UTC, markcmurphy submitted a review, later dismissed

2021-03-11 14:26 UTC, uwikaiddi requested changes

2021-03-11 14:26 UTC, uwikaiddi commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Errors?**
```suggestion
### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Errors?
```

2021-03-11 14:26 UTC, uwikaiddi commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +The [Checkout SDK's](https://github.com/bigcommerce/checkout-sdk-js) [`embedded-checkout` sub-module](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/README.md#embedcheckout) can be u
```suggestion
The [Checkout SDK's`embedded-checkout` sub-module](https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/README.md#embedcheckout) can be used to embed [BigCommerce's Optimized One-Page Checkout](https://support.bigcommerce.com/s/article/Optimized-Single-Page-Checkout) into non-native storefronts like WordPress. You can see this in action within the BigCommerce for WordPress plugin, which uses the same process described here as a checkout option for merchants. For more information about the plugin, see [BigCommerce for Wordpress](https://developer.bigcommerce.com/bigcommerce-for-wordpress/getting-started/introduction).
```

2021-03-11 14:26 UTC, uwikaiddi commented on docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
> +For Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your BigCommerce
```suggestion
For Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your BigCommerce storefront. For example, if your headless storefront is `www.mystore.com`, then your BigCommerce store's domain should be `checkout.mystore.com`. For more information on making Embedded Checkout on a headless WordPress storefront compatible with Safari, see [BigCommerce for WordPress](https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout#safari).
```

2021-03-11 14:26 UTC, uwikaiddi commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Errors?**
```suggestion
### How do I resolve Embedded Checkout 403 "Cannot start checkout session with an empty cart" Errors?
```

2021-03-11 14:26 UTC, uwikaiddi commented on docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
> +For Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your BigCommerce
```suggestion
For Embedded Checkout to work correctly for shoppers using a browser with restricted privacy settings (like Apple's Safari), your checkout page must be served from the same domain as your BigCommerce storefront. For example, if your headless storefront is `www.mystore.com`, then your BigCommerce store's domain should be `checkout.mystore.com`. For more information on making Embedded Checkout on a headless WordPress storefront compatible with Safari, see [BigCommerce for WordPress](https://support.bigcommerce.com/s/article/BigCommerce-for-WordPress-Checkout#safari).
```

2021-03-12 14:33 UTC, uwikaiddi approved these changes

2021-03-12 14:34 UTC, merged