DEVDOCS-2554: Updated Customers and Subscribers
bigcommerce/dev-docs pull request #980
Opened 2021-02-17 22:35 UTC by ektravel

# [DEVDOCS-2554](https://jira.bigcommerce.com/browse/DEVDOCS-)

## What changed?
* added links to Customer Login and Current Customer APIs
* Updated "On This Page"

2021-02-18 19:26 UTC, traci707 submitted a review, later dismissed
LGTM

2021-02-18 20:34 UTC, uwikaiddi requested changes

2021-02-18 20:34 UTC, uwikaiddi commented on docs/api-docs/customers/customers-subscribers-overview.md
@ektravel, please add a transition sentence here. We want to avoid headers having no transitions into their subheaders.

2021-02-22 18:37 UTC, closed without merging

2021-02-22 18:37 UTC, ektravel commented
Closing this PR due to a merge conflict. See new [PR 986](https://github.com/bigcommerce/dev-docs/pull/986).