Updated supported-features.md
bigcommerce/dev-docs pull request #988
Opened 2021-02-23 14:34 UTC by traci707

# [DEVDOCS-2424](https://jira.bigcommerce.com/browse/DEVDOCS-2424)

## What changed?
Removed Chase Pay from BigCommerce Documentation

2021-02-23 15:37 UTC, markcmurphy approved these changes

2021-02-24 14:20 UTC, uwikaiddi requested changes

2021-02-24 14:20 UTC, uwikaiddi commented on docs/bigcommerce-for-wordpress/getting-started/supported-features.md
> +Unsupported hosted payment gateways are Amazon Pay, AfterPay, Google Pay, and Masterpass.
```suggestion
### Unsupported payment gateways

The following payment gateways are currently not supported:

* Amazon Pay
* AfterPay
* Google Pay
* Masterpass

```

2021-02-26 22:22 UTC, uwikaiddi approved these changes

2021-02-26 22:22 UTC, merged